Repository ManageIQ/manageiq-providers-google, pull requests merged in 2018-11, with the labels that each got.

#80 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Google.po
  locale/fr/ManageIQ_Providers_Google.po
  locale/ja/ManageIQ_Providers_Google.po
  locale/pt_BR/ManageIQ_Providers_Google.po
  locale/zh_CN/ManageIQ_Providers_Google.po
Labels: internationalization

#81 Always set vm_or_template.connection_state
  app/models/manageiq/providers/google/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/google/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb
Labels: bug

#82 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation
