Repository ManageIQ/manageiq-providers-google, pull requests merged in 2018-09, with the labels that each got.

#67 Google graph refresh
  app/models/manageiq/providers/google/cloud_manager/refresher.rb
  app/models/manageiq/providers/google/inventory.rb
  app/models/manageiq/providers/google/inventory/collector.rb
  app/models/manageiq/providers/google/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/google/inventory/collector/network_manager.rb
  app/models/manageiq/providers/google/inventory/parser.rb
  app/models/manageiq/providers/google/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/google/inventory/parser/network_manager.rb
  app/models/manageiq/providers/google/inventory/persister.rb
  app/models/manageiq/providers/google/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/google/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/google/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/google/inventory/persister/network_manager.rb
  app/models/manageiq/providers/google/network_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb
Labels: enhancement, inventory

#72 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#74 Actually test both graph and standard refresh
  spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb
Labels: test

#75 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
