Repository ManageIQ/manageiq-providers-google, pull requests merged in 2018-06, with the labels that each got.

#60 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#59 Follow up on #54 "Fog google upgrade (to 1.3.3)" code cleanup
  app/models/manageiq/providers/google/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/google/network_manager/refresh_parser.rb
Labels: refactoring

#61 Add display name for flavor
  app/models/manageiq/providers/google/cloud_manager/flavor.rb
Labels: enhancement

#65 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation
