Repository ManageIQ/manageiq-providers-google, pull requests merged in 2020-10, with the labels that each got.

#159 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#161 require a minimum googleauth for faraday 1.0
  manageiq-providers-google.gemspec
Labels: dependencies

#160 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-google.gemspec
Labels: developer, enhancement

#162 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
