Repository ManageIQ/manageiq-providers-google, pull requests merged in 2020-12, with the labels that each got.

#170 Fix refresh failure when load balancer can't be found
  app/models/manageiq/providers/google/inventory/parser/network_manager.rb
Labels: bug, kasparov/yes?

#172 Remove unused settings section
  config/settings.yml
Labels: technical debt

#173 Fix linter warnings - unused variable, ineffective access modifier
  app/models/manageiq/providers/google/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/google/cloud_manager/provision_workflow.rb
Labels: technical debt

#174 manageiq-style -i
  .codeclimate.yml
Labels: developer
