Repository ManageIQ/manageiq-providers-google, pull requests merged in 2020-03, with the labels that each got.

#112 Fix for some networks not having subnets
  app/models/manageiq/providers/google/inventory/collector/network_manager.rb
  app/models/manageiq/providers/google/inventory/parser/network_manager.rb
Labels: bug, ivanchuk/yes

#124 Remove bogus partial, update variable name
  spec/models/manageiq/providers/google/cloud_manager_spec.rb
Labels: refactoring, test

#125 remove inventory object refresh
  app/models/manageiq/providers/google/cloud_manager.rb
  app/models/manageiq/providers/google/network_manager.rb
Labels: cleanup

#126 Remove unused ems_inv_to_hashes method
  app/models/manageiq/providers/google/inventory/parser.rb
  app/models/manageiq/providers/google/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/google/inventory/parser/network_manager.rb
  app/models/manageiq/providers/google/refresh_helper_methods.rb
Labels: cleanup
