Repository ManageIQ/manageiq-providers-google, pull requests merged in 2020-05, with the labels that each got.

#131 Catch errors listing load_balancer health_members
  app/models/manageiq/providers/google/inventory/parser/network_manager.rb
Labels: bug, jansa/yes?

#132 Adjusted DDF schema and removed create/edit methods
  app/models/manageiq/providers/google/manager_mixin.rb
Labels: enhancement

#133 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#134 Removing deprecated Gemnasium badge
  README.md
Labels: developer
