Repository ManageIQ/manageiq-providers-google, pull requests merged in 2020-09, with the labels that each got.

#153 Update the fog-google gem
  manageiq-providers-google.gemspec
  spec/vcr_cassettes/manageiq/providers/google/cloud_manager/refresher.yml
Labels: dependencies

#149 update fog for faraday
  manageiq-providers-google.gemspec
Labels: dependencies

#156 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/google/manager_mixin.rb
Labels: bug

#157 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/google/manager_mixin.rb
Labels: enhancement
