Repository ManageIQ/manageiq-providers-google, pull requests merged in 2021-03, with the labels that each got.

#181 Don't manually set the templates model_class
  app/models/manageiq/providers/google/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring

#182 Use combined refresh support from core
  app/models/manageiq/providers/google/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/google/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/google/inventory/persister/network_manager.rb
Labels: refactoring

#183 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#178 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-google_cloud_manager_event_catcher.target
  build/systemd_units/manageiq-providers-google_cloud_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-google_cloud_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-google_cloud_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-google_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-google_cloud_manager_refresh@.service
  build/systemd_units/manageiq-providers-google_network_manager_refresh.target
  build/systemd_units/manageiq-providers-google_network_manager_refresh@.service
Labels: technical debt
