Repository ManageIQ/manageiq-providers-google, pull requests merged in 2022-07, with the labels that each got.

#228 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
Labels: developer

#229 Converting keys to strings
  app/models/manageiq/providers/google/cloud_manager/cloud_database.rb
  spec/models/manageiq/providers/google/cloud_manager/cloud_database_spec.rb
Labels: bug

#230 Removing memoization
  app/models/manageiq/providers/google/manager_mixin.rb
Labels: bug, najdorf/yes?
