Repository ManageIQ/manageiq-providers-google, pull requests merged in 2024-02, with the labels that each got.

#258 Drop require_nested and include_concern
  app/models/manageiq/providers/google/cloud_manager.rb
  app/models/manageiq/providers/google/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/google/cloud_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/google/cloud_manager/provision.rb
  app/models/manageiq/providers/google/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/google/cloud_manager/vm.rb
  app/models/manageiq/providers/google/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/google/container_manager.rb
  app/models/manageiq/providers/google/container_manager/event_catcher.rb
  app/models/manageiq/providers/google/container_manager/refresh_worker.rb
  app/models/manageiq/providers/google/inventory.rb
  app/models/manageiq/providers/google/inventory/collector.rb
  app/models/manageiq/providers/google/inventory/collector/container_manager.rb
  app/models/manageiq/providers/google/inventory/parser.rb
  app/models/manageiq/providers/google/inventory/parser/container_manager.rb
  app/models/manageiq/providers/google/inventory/persister.rb
  app/models/manageiq/providers/google/inventory/persister/container_manager.rb
  app/models/manageiq/providers/google/network_manager.rb
Labels: technical debt, rails7

#259 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#261 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#260 drop use of unuspported_reason_add
  app/models/manageiq/providers/google/cloud_manager.rb
  app/models/manageiq/providers/google/cloud_manager/template.rb
  app/models/manageiq/providers/google/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/google/cloud_manager/vm/operations/guest.rb
Labels: refactoring, radjabov/yes?
